---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The infrastructure of the 100DaysOfCloud website.


Parameters:
  ProjectName:
    Description: The name of the project. It will be used to name and tag resources.
    Type: String
    Default: "100DaysOfCloudWebsite"
  ClientDomains:
    Description: Array of domains allowed to use the Cognito User Pool.
    Type: CommaDelimitedList

Resources:
  # S3
  ## Static site hosting bucket
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
      CorsConfiguration:
        CorsRules:
          - 
            AllowedMethods: 
              - GET
              - HEAD
            AllowedOrigins: 
              - "*"
            AllowedHeaders: 
              - "*"
      Tags:
        - Key: CostCenter
          Value: !Sub "${ProjectName}"

  # Bucket for CodePipeline artifacts
  ArtifactsBucket:
    Type: AWS::S3::Bucket

  ## CloudFront OAI for the website bucket policy
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: !Sub "The OAI for the ${ProjectName} project and bucket: ${WebsiteBucket}"

  ## Bucket policy of the static website hosting bucket
  WebsiteBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Id: PublicAccessPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

  
  ## Cloudfront distribution
  WebsiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub "${WebsiteBucket}.s3.amazonaws.com"
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        Enabled: 'true'
        Comment: !Sub "${ProjectName} distribution"
        DefaultRootObject: index.html
        # FIXME when domain switching
        # Aliases:
        #   - !Ref WebsiteDomainName
        #   - !Sub "www.${WebsiteDomainName}"
        DefaultCacheBehavior:
          DefaultTTL: 1800
          MaxTTL: 14400
          Compress: true
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          CachedMethods:
            - HEAD
            - GET
            - OPTIONS
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        # FIXME when domain switching
        # ViewerCertificate:
        #   AcmCertificateArn: !Ref DomainCertificate
        #   SslSupportMethod: sni-only 

  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: github_username
        Type: String

  APIs:
    Type: AWS::Serverless::Application
    Properties:
      Location: 'SAM/API/api.template.yml'
      Parameters:
        UsersTable: !Ref UsersTable

  ### Only deploy later when creating the Cognito pool is needed
  # Cognito:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: 'SAM/cognito.template.yml'
  #     Parameters:
  #       ClientDomains: !Ref ClientDomains